* Chicken Chettinad

This is one of the best chicken recipes you may have tried yet. Bring some magic to your plate with chicken cooked in some peppery authentic Chettinad paste laced with coconut and onions.

** Source
http://food.ndtv.com/recipe-chicken-chettinad-218316

Chef: Kishore D Reddy

** Ingredients

+ 500 gm chicken
+ 75 ml oil
+ 150 gm onions
+ 100 gm tomatoes
+ 2 gm cinnamon sticks
+ 2 gm cloves
+ 2 gm cardamoms
+ 5 gm cumin
+ 2 gm curry leaves
+ 10 gm turmeric powder
+ Salt
+ 25 gm coriander leaves

** Paste:

+ 100 gm onions
+ 50 gm ginger
+ 50 gm garlic
+ 50 gm fennel seeds
+ 20 gm cumin seeds
+ 25 gm peppercorns
+ 10 gm red chillies
+ 100 gm coconut

** Preparation

+ Grind the ingredients for the paste.
+ Clean and cut the chicken into 16 pieces. Marinate the chicken with the paste.
+ Chop the tomatoes, coriander leaves and the onions.
+ Heat oil and add the cinnamon, cardamom, cloves and cumin, Saute.
+ Add the chopped onions and the curry leaves. Saute until the onions are golden.
+ Add the tomatoes and saute for 5 minutes.
+ Add the marinated chicken and turmeric powder. Saute for 10 minutes, sprinkling water at intervals.
+ Add enough salt, cover with a lid and cook until done. Add more chilli or pepper if required.
+ Serve garnished with coriander leaves.
