* Kadhi Pakora

** Making Curd Slurry
+ In a bowl take 1.5 cups sour curd or about 375 grams of curd. Whisk it well till smooth.
+ Add 8 tbsp gram flour (besan), 1/2 tbsp red chilli powder, 1/2 tsp turmeric powder,
  1/2 tsp garam masala powder and 1 tsp salt to the whisked curd.
+ Stir and mix everything again.
+ Add 3 cups water and stir again.
+ Stir very well to make a smooth mixture without lumps. If there are lumps, then break them with a
  wired whisk or a spatula or with your fingers. Set the curd slurry aside.
+ Make onion pakora.
** Making kadhi
+ heat 2 tbsp miustard oil. Add 1 tsp cumin seeds, 8 to 10 fenugreek seeds (methi) and a generous pinch of
  asafoetida (hing). Allow the cummin seeds to crackle and the fenugreek seeds to change their color.
  Fry on a low flame, so that these spices do not get burnt.
+ Add 1/3 cup chopped onion. Stir and saute for 3 minutes on a low flame.
+ Add 1 tbsp chopped ginger, 3/4 to 1 tbsp chopped garlic and 2 green chillies, chopped. Stir and saute
  for a minute.
+ Now add 8 to 10 curry leaves, 2 dry red chillies (halved or broken).
+ Stir and saute for a minutes on a low flame.
+ Then add the curd slurry.
+ Stir very well.
+ Increase the flame to medium and bring the kadhi to a boil. Keep on stirring
  often so that the bottom does not get browned. Time taken to cook kadhi will
  be around 14 to 16 minutes.
+ After the kadhi comes to a boil, then lower the flame and simmer it for
  further 6 to 7 minutes. Do stir at times. The kadhi will thicken. If it
  becomes too thick, then add some hot water.
+ Now add the onion pakora to the kadhi. Stir gently.
+ Cover with a lid and let the onion pakora be soaked in it for 8 to 10 minutes.
+ Lastly, sprinkle some garam masala powder on the Punjabi Kadhi.
